[package]
name = "senbit"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "senbit"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
anyhow = "1.0.104"
argon2 = "0.6.0"
colored = "3.1.1"
inquire = "0.9.4"
libc = "0.2.189"
rand = "0.10.3"
reqwest = { version = "0.13.5", features = ["blocking"] }
tempfile = "3.27.0"
